'use client'

import { Calendar, CheckCircle2, ShieldCheck, Sparkles, Wallet } from 'lucide-react'
import { PageHeading, SectionTitle, StatCard } from '@/components/dashboard-ui'

export default function MaintenancePage() {
  return <div className="mx-auto flex max-w-7xl flex-col gap-8"><PageHeading eyebrow="Preventive care" title="Maintenance, before it becomes a problem" description="Stay ahead of repairs with intelligent reminders, complete service history, and AI-powered health monitoring." />
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Upcoming services" value="No data" detail="No maintenance records yet" icon={Calendar} delay={0} /><StatCard label="Completed this year" value="No data" detail="No maintenance records yet" icon={CheckCircle2} delay={60} /><StatCard label="Maintenance spend" value="No data" detail="No maintenance records yet" icon={Wallet} delay={120} /><StatCard label="Fleet health" value="No data" detail="Add maintenance records to calculate it" icon={ShieldCheck} delay={180} /></section>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><section className="glass animate-rise rounded-2xl p-5 sm:p-6 lg:col-span-2"><SectionTitle title="Service timeline" description="All maintenance activity in chronological order" /><div className="mt-6 rounded-xl border border-border bg-secondary/30 px-5 py-14 text-center"><Calendar className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 text-sm font-semibold text-foreground">No maintenance records yet</p><p className="mx-auto mt-1 max-w-sm text-xs leading-relaxed text-muted-foreground">Maintenance persistence is not implemented in this project, so no sample services or costs are shown.</p></div></section><div className="flex flex-col gap-6"><section className="glass-strong grid-texture animate-rise rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><div><h2 className="text-sm font-semibold text-foreground">Predictive maintenance</h2><p className="text-[11px] text-muted-foreground">AI health forecast</p></div></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Add maintenance records to enable health forecasts and service reminders for your vehicles.</p></section><section className="glass animate-rise rounded-2xl p-5 sm:p-6"><SectionTitle title="Cost overview" description="Maintenance spending" /><div className="mt-5 rounded-xl border border-border bg-secondary/30 p-5 text-center"><Wallet className="mx-auto size-6 text-muted-foreground" /><p className="mt-2 text-xs text-muted-foreground">Cost insights will appear once maintenance tracking is connected.</p></div></section></div></div>
  </div>
}
