'use client'

import { Mail, Shield, User } from 'lucide-react'
import { PageHeading, SectionTitle } from '@/components/dashboard-ui'
import { getUserDisplayName, getUserInitials, useAuth } from '@/components/providers/auth-provider'

export default function SettingsPage() {
  const { user } = useAuth()
  const name = user ? getUserDisplayName(user) : 'User'
  const initials = user ? getUserInitials(user) : 'DW'
  return <div className="mx-auto flex max-w-6xl flex-col gap-8"><PageHeading eyebrow="Workspace controls" title="Settings" description="View the account information used in your DriveWise workspace." /><section className="glass animate-rise rounded-2xl p-5 sm:p-6"><SectionTitle title="Profile details" description="This information comes from your authenticated DriveWise account." /><div className="mt-6 flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex size-20 shrink-0 items-center justify-center rounded-2xl bg-primary/15 text-xl font-semibold text-primary ring-1 ring-primary/20" aria-label="DriveWise profile avatar">{initials}</div><div><h3 className="text-base font-semibold text-foreground">{name}</h3><p className="mt-1 text-sm text-muted-foreground">DriveWise account profile</p></div></div><div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><ProfileField icon={User} label="Full name" value={user?.displayName?.trim() || 'Not provided'} /><ProfileField icon={Mail} label="Email address" value={user?.email || 'Not available'} /></div></section><section className="glass animate-rise rounded-2xl p-5 sm:p-6"><SectionTitle title="Privacy & data" description="DriveWise uses your authenticated account to scope vehicles, fuel logs, and maintenance records." /><div className="mt-6 rounded-xl border border-border bg-secondary/30 p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Shield className="size-4" /></div><div><p className="text-sm font-medium text-foreground">Your workspace data</p><p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">Vehicle, fuel, and maintenance records are stored only for the signed-in account. AI guidance is based on the context sent with your question.</p></div></div></div></section></div>
}
function ProfileField({ icon: Icon, label, value }: { icon: typeof User; label: string; value: string }) { return <div className="rounded-xl border border-border bg-secondary/30 p-4"><div className="flex items-center gap-2 text-muted-foreground"><Icon className="size-4" /><span className="text-xs font-medium">{label}</span></div><p className="mt-2 break-words text-sm text-foreground">{value}</p></div> }
